//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileProcessorEFDALLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public string OrderId { get; set; }
        public string OrderReferenceNumber { get; set; }
        public string OrderCustomerId { get; set; }
        public string OrderDate { get; set; }
    }
}
